<?php

namespace Database\Seeders;

use App\Models\Destination;
use App\Models\Category;
use Illuminate\Database\Seeder;

class DestinationSeeder extends Seeder
{
    public function run(): void
    {
        $budayaId = Category::where('slug', 'budaya-sejarah')->value('id');
        $kulinerID = Category::where('slug', 'kuliner')->value('id');
        $alamId = Category::where('slug', 'alam-taman')->value('id');
        $belanjaId = Category::where('slug', 'belanja-pasar')->value('id');
        $seniId = Category::where('slug', 'seni-pertunjukan')->value('id');
        $religiId = Category::where('slug', 'religi-ziarah')->value('id');

        $destinations = [
            [
                'category_id' => $budayaId,
                'name' => 'Keraton Kasunanan Surakarta',
                'slug' => 'keraton-kasunanan-surakarta',
                'description' => 'Istana resmi Kasunanan Surakarta yang dibangun pada tahun 1745. Keraton ini merupakan pusat kebudayaan Jawa dan menjadi salah satu destinasi wisata utama di Kota Solo. Di sini Anda dapat menyaksikan koleksi pusaka kerajaan, gamelan bersejarah, dan berbagai artefak budaya Jawa.',
                'address' => 'Jl. Sidikoro No.1, Baluwarti, Kec. Ps. Kliwon, Kota Surakarta',
                'lat' => -7.5740,
                'lng' => 110.8264,
                'price' => 15000,
                'opening_hours' => 'Senin-Kamis 09:00-14:00, Sabtu-Minggu 09:00-14:00',
                'image_url' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Surakarta_Kraton.jpg/640px-Surakarta_Kraton.jpg',
                'estimated_duration' => 90,
                'rating' => 4.5,
                'review_count' => 0,
                'tips' => 'Gunakan pakaian sopan saat berkunjung. Tersedia pemandu wisata lokal dengan biaya tambahan.',
            ],
            [
                'category_id' => $budayaId,
                'name' => 'Pura Mangkunegaran',
                'slug' => 'pura-mangkunegaran',
                'description' => 'Istana megah milik Kerajaan Mangkunegaran yang dibangun pada 1757. Terkenal dengan pendopo (aula pertemuan) besarnya yang merupakan salah satu yang terbesar di Asia Tenggara. Koleksi museum mencakup topeng Jawa, keris, dan koleksi pribadi Mangkunegaran.',
                'address' => 'Jl. Ronggowarsito, Keprabon, Kec. Banjarsari, Kota Surakarta',
                'lat' => -7.5664,
                'lng' => 110.8245,
                'price' => 20000,
                'opening_hours' => 'Senin-Sabtu 09:00-14:00',
                'image_url' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Pura_Mangkunegaran_Surakarta.jpg/640px-Pura_Mangkunegaran_Surakarta.jpg',
                'estimated_duration' => 90,
                'rating' => 4.7,
                'review_count' => 0,
                'tips' => 'Dilarang masuk ke area tertentu tanpa izin. Beli tiket di loket resmi.',
            ],
            [
                'category_id' => $budayaId,
                'name' => 'Museum Radya Pustaka',
                'slug' => 'museum-radya-pustaka',
                'description' => 'Museum tertua di Indonesia yang didirikan pada 1890, menyimpan koleksi naskah kuno, senjata tradisional, wayang, dan benda-benda bersejarah Kerajaan Jawa. Terletak di kawasan Sriwedari yang strategis.',
                'address' => 'Jl. Slamet Riyadi No.275, Sriwedari, Kec. Laweyan, Kota Surakarta',
                'lat' => -7.5682,
                'lng' => 110.8154,
                'price' => 5000,
                'opening_hours' => 'Selasa-Minggu 08:00-17:00',
                'image_url' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Museum_Radya_Pustaka_Solo.jpg/640px-Museum_Radya_Pustaka_Solo.jpg',
                'estimated_duration' => 60,
                'rating' => 4.2,
                'review_count' => 0,
                'tips' => 'Buka setiap hari kecuali Senin. Sangat cocok untuk pelajar dan peneliti sejarah.',
            ],
            [
                'category_id' => $kulinerID,
                'name' => 'Nasi Liwet Bu Wongso Lemu',
                'slug' => 'nasi-liwet-bu-wongso-lemu',
                'description' => 'Warung legendaris yang menjual nasi liwet khas Solo sejak puluhan tahun. Nasi liwet disajikan di atas daun pisang dengan ayam opor, areh (santan kental), dan lauk pauk lainnya. Wajib dicoba sebagai kuliner autentik Solo.',
                'address' => 'Jl. Teuku Umar, Keprabon, Kec. Banjarsari, Kota Surakarta',
                'lat' => -7.5652,
                'lng' => 110.8232,
                'price' => 25000,
                'opening_hours' => 'Setiap hari 17:00-23:00',
                'image_url' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/56/Nasi_liwet_Solo.jpg/640px-Nasi_liwet_Solo.jpg',
                'estimated_duration' => 45,
                'rating' => 4.8,
                'review_count' => 0,
                'tips' => 'Datang sebelum jam 7 malam karena bisa habis. Makan di tempat untuk pengalaman terbaik.',
            ],
            [
                'category_id' => $kulinerID,
                'name' => 'Timlo Sastro',
                'slug' => 'timlo-sastro',
                'description' => 'Warung timlo paling legendaris di Solo yang sudah berdiri sejak 1952. Timlo adalah sup khas Solo berisi sosis Solo, telur pindang, hati ampela, dan irisan daging ayam dalam kaldu bening yang gurih.',
                'address' => 'Jl. Urip Sumoharjo No.96, Purwosari, Kec. Laweyan, Kota Surakarta',
                'lat' => -7.5644,
                'lng' => 110.8328,
                'price' => 20000,
                'opening_hours' => 'Setiap hari 06:00-22:00',
                'image_url' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Timlo_solo.jpg/640px-Timlo_solo.jpg',
                'estimated_duration' => 30,
                'rating' => 4.6,
                'review_count' => 0,
                'tips' => 'Ramai saat makan siang dan malam. Pesan nasi putih atau lontong sebagai pelengkap.',
            ],
            [
                'category_id' => $kulinerID,
                'name' => 'Sate Kambing Pak Manto',
                'slug' => 'sate-kambing-pak-manto',
                'description' => 'Warung sate kambing terkenal di Solo yang menggunakan daging kambing segar pilihan. Sate disajikan dengan bumbu kacang atau kecap yang khas, dilengkapi dengan lontong atau nasi. Tempat makan favorit warga lokal.',
                'address' => 'Jl. Honggowongso No.28, Serengan, Kota Surakarta',
                'lat' => -7.5792,
                'lng' => 110.8354,
                'price' => 35000,
                'opening_hours' => 'Setiap hari 11:00-22:00',
                'image_url' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/63/Sate_kambing.jpg/640px-Sate_kambing.jpg',
                'estimated_duration' => 45,
                'rating' => 4.5,
                'review_count' => 0,
                'tips' => 'Pilih sate bagian gigit untuk tekstur lebih empuk. Minta tambah bumbu jika suka pedas.',
            ],
            [
                'category_id' => $alamId,
                'name' => 'Taman Balekambang',
                'slug' => 'taman-balekambang',
                'description' => 'Taman hiburan rakyat yang dibangun pada 1921 oleh KGPAA Mangkunegara VII untuk kedua putrinya. Taman seluas 9,8 hektar ini memiliki danau buatan, hutan kota, dan berbagai fasilitas rekreasi. Tempat bersantai favorit keluarga Solo.',
                'address' => 'Jl. Ahmad Yani, Manahan, Kec. Banjarsari, Kota Surakarta',
                'lat' => -7.5554,
                'lng' => 110.8220,
                'price' => 10000,
                'opening_hours' => 'Setiap hari 06:00-17:00',
                'image_url' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/Taman_Balekambang_Solo.jpg/640px-Taman_Balekambang_Solo.jpg',
                'estimated_duration' => 120,
                'rating' => 4.3,
                'review_count' => 0,
                'tips' => 'Cocok untuk piknik keluarga. Bawa bekal makanan sendiri karena warung di dalam agak mahal.',
            ],
            [
                'category_id' => $alamId,
                'name' => 'Kebun Binatang Jurug',
                'slug' => 'kebun-binatang-jurug',
                'description' => 'Kebun binatang terbesar di Solo yang terletak di tepi Sungai Bengawan Solo. Memiliki berbagai koleksi satwa liar termasuk harimau, orangutan, buaya, dan berbagai jenis burung. Dilengkapi dengan taman bermain anak.',
                'address' => 'Jl. Ir. Juanda No.109, Jebres, Kota Surakarta',
                'lat' => -7.5595,
                'lng' => 110.8524,
                'price' => 15000,
                'opening_hours' => 'Setiap hari 07:00-17:00',
                'image_url' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Jurug_Zoo.jpg/640px-Jurug_Zoo.jpg',
                'estimated_duration' => 180,
                'rating' => 4.0,
                'review_count' => 0,
                'tips' => 'Datang pagi hari saat hewan lebih aktif. Bawa topi dan sunscreen.',
            ],
            [
                'category_id' => $belanjaId,
                'name' => 'Pasar Klewer',
                'slug' => 'pasar-klewer',
                'description' => 'Pasar tekstil dan batik terbesar di Jawa Tengah, bahkan menjadi salah satu pasar batik terbesar di Indonesia. Menawarkan berbagai pilihan kain batik Solo dari yang murah hingga premium. Wajib dikunjungi pecinta batik.',
                'address' => 'Jl. DR. Radjiman No.5, Gajahan, Kec. Ps. Kliwon, Kota Surakarta',
                'lat' => -7.5729,
                'lng' => 110.8248,
                'price' => 0,
                'opening_hours' => 'Setiap hari 08:00-17:00',
                'image_url' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/51/Pasar_Klewer_Solo.jpg/640px-Pasar_Klewer_Solo.jpg',
                'estimated_duration' => 120,
                'rating' => 4.4,
                'review_count' => 0,
                'tips' => 'Jangan lupa tawar harga! Datang pagi untuk pilihan paling lengkap. Hati-hati copet.',
            ],
            [
                'category_id' => $belanjaId,
                'name' => 'Pasar Triwindu',
                'slug' => 'pasar-triwindu',
                'description' => 'Pasar antik dan barang koleksi yang terletak dekat Pura Mangkunegaran. Menjual berbagai barang antik seperti wayang, topeng, keris, batik lama, perabot antik, dan souvenir khas Jawa. Surga para kolektor barang antik.',
                'address' => 'Jl. Diponegoro, Keprabon, Kec. Banjarsari, Kota Surakarta',
                'lat' => -7.5652,
                'lng' => 110.8215,
                'price' => 0,
                'opening_hours' => 'Setiap hari 08:00-17:00',
                'image_url' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7e/Triwindu_market_Solo.jpg/640px-Triwindu_market_Solo.jpg',
                'estimated_duration' => 90,
                'rating' => 4.3,
                'review_count' => 0,
                'tips' => 'Tawar dengan santun karena penjual biasanya sangat kooperatif. Periksa keaslian barang antik.',
            ],
            [
                'category_id' => $seniId,
                'name' => 'Wayang Orang Sriwedari',
                'slug' => 'wayang-orang-sriwedari',
                'description' => 'Pertunjukan wayang orang (wayang dengan manusia sebagai pemain) yang telah berlangsung sejak 1901, menjadikannya salah satu pertunjukan wayang orang terlama di dunia. Berlokasi di Taman Hiburan Sriwedari, pertunjukan ini menyajikan cerita epik Ramayana dan Mahabharata.',
                'address' => 'Gedung Kesenian Sriwedari, Jl. Slamet Riyadi No.275, Kota Surakarta',
                'lat' => -7.5673,
                'lng' => 110.8152,
                'price' => 20000,
                'opening_hours' => 'Senin-Sabtu 20:00-23:00',
                'image_url' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/Wayang_orang_sriwedari.jpg/640px-Wayang_orang_sriwedari.jpg',
                'estimated_duration' => 180,
                'rating' => 4.6,
                'review_count' => 0,
                'tips' => 'Pertunjukan dimulai jam 8 malam. Beli tiket lebih awal di akhir pekan. Bawa jaket karena AC ruangan cukup dingin.',
            ],
            [
                'category_id' => $seniId,
                'name' => 'ISI Surakarta',
                'slug' => 'isi-surakarta',
                'description' => 'Institut Seni Indonesia Surakarta, kampus seni bergengsi yang sering mengadakan pertunjukan seni gratis untuk umum. Pengunjung dapat menyaksikan latihan gamelan, tari Jawa, dan berbagai pertunjukan seni tradisional.',
                'address' => 'Jl. Ki Hajar Dewantara No.19, Kentingan, Kec. Jebres, Kota Surakarta',
                'lat' => -7.5562,
                'lng' => 110.8450,
                'price' => 0,
                'opening_hours' => 'Senin-Jumat 08:00-16:00',
                'image_url' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/ISI_Surakarta.jpg/640px-ISI_Surakarta.jpg',
                'estimated_duration' => 90,
                'rating' => 4.4,
                'review_count' => 0,
                'tips' => 'Cek jadwal pertunjukan di papan pengumuman kampus. Hormati privasi mahasiswa yang sedang berlatih.',
            ],
            [
                'category_id' => $religiId,
                'name' => 'Masjid Agung Surakarta',
                'slug' => 'masjid-agung-surakarta',
                'description' => 'Masjid kerajaan yang dibangun pada tahun 1750 bersamaan dengan pembangunan Keraton Kasunanan. Merupakan salah satu masjid bersejarah terpenting di Indonesia dengan arsitektur Jawa-Islam yang memukau. Terletak di alun-alun utara Keraton.',
                'address' => 'Jl. Masjid Agung No.1, Kauman, Kec. Ps. Kliwon, Kota Surakarta',
                'lat' => -7.5716,
                'lng' => 110.8256,
                'price' => 0,
                'opening_hours' => 'Setiap hari 05:00-21:00',
                'image_url' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Masjid_Agung_Surakarta.jpg/640px-Masjid_Agung_Surakarta.jpg',
                'estimated_duration' => 60,
                'rating' => 4.7,
                'review_count' => 0,
                'tips' => 'Gunakan pakaian sopan dan menutup aurat. Tidak diperbolehkan masuk saat jam sholat bagi non-Muslim.',
            ],
            [
                'category_id' => $religiId,
                'name' => 'Makam Laweyan',
                'slug' => 'makam-laweyan',
                'description' => 'Kompleks makam kuno yang berada di kawasan Laweyan, berisi makam para bangsawan dan tokoh penting Kerajaan Pajang dan Mataram. Kawasan Laweyan sendiri merupakan kampung batik tertua di Solo dengan sejarah lebih dari 500 tahun.',
                'address' => 'Kampung Laweyan, Kec. Laweyan, Kota Surakarta',
                'lat' => -7.5705,
                'lng' => 110.8032,
                'price' => 5000,
                'opening_hours' => 'Setiap hari 08:00-17:00',
                'image_url' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Laweyan_Solo.jpg/640px-Laweyan_Solo.jpg',
                'estimated_duration' => 60,
                'rating' => 4.1,
                'review_count' => 0,
                'tips' => 'Kombinasikan kunjungan dengan wisata kampung batik Laweyan di sekitarnya. Bawa air minum sendiri.',
            ],
        ];

        foreach ($destinations as $destination) {
            Destination::create($destination);
        }
    }
}
